name: SQL
run-name: SQL Test
on: [push]
jobs:
  SQL-Test:
    runs-on: ubuntu-latest
    steps:


      - run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE test;' -uroot -proot
          mysql -e 'USE test; CREATE TABLE tabl (tags varchar(255), ID int) ;' -uroot -proot 
          mysql -e 'USE test; insert into tabl(tags,ID) values ("Python",1);' -uroot -proot 
          mysql -e 'USE test; insert into tabl(tags,ID) values ("C++",2);' -uroot -proot 
          mysql -e 'USE test; insert into tabl(tags,ID) values ("JavaScript",3);' -uroot -proot 
          mysql -e 'USE test; insert into tabl(tags,ID) values ("MySQL",4);' -uroot -proot 
          mysql -e 'USE test; insert into tabl(tags,ID) values ("Java",5);' -uroot -proot 
          mysql -e 'USE test; select * from tabl;' -uroot -proot 
          
          
